version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
    ports:
      - "8080:8080"

  booking-service:
    build:
      context: ./services/booking-service
    ports:
      - "8081:8080"

  occupancy-service:
    build:
      context: ./services/occupancy-service
    ports:
      - "8082:8080"