version: '3.8'

services:
  auth-service:
    container_name: spaceflow-auth-service
    build:
      context: ./services/auth-service
    ports:
      - "8080:8080"

  booking-service:
    container_name: spaceflow-booking-service
    build:
      context: ./services/booking-service
    ports:
      - "8081:8080"

  occupancy-service:
    container_name: spaceflow-occupancy-service
    build:
      context: ./services/occupancy-service
    ports:
      - "8082:8080"

  analytics-service:
    container_name: spaceflow-analytics-service
    build:
      context: ./services/analytics-service
    ports:
      - "8083:8080"

  ai-engine:
    container_name: spaceflow-ai-engine
    build:
      context: ./services/ai-engine
    ports:
      - "8084:8080"